---
title: "**Map**"
output: 
  html_document:
    toc: true
    toc_float: true
    theme:  flatly
    css: index.css
    code_folding: hide
---

### **Map: Distribution of Crime Rate From 2016 to 2021 in Chicago**
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(leaflet)
library(httr)
library(plotly)
library(dplyr)
library(magrittr)
library(readr)
```

```{r, message=FALSE}
#data loading
crime_2017 =
   read.csv("./Data/Crimes_-_2017.csv") %>% 
   drop_na() %>% 
   janitor::clean_names() %>%
   filter(arrest=="true",domestic=="true")

map2017 = crime_2017 %>%
leaflet() %>%
addProviderTiles(providers$Esri.WorldImagery, group = "World Imagery") %>%
addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
addLayersControl(baseGroups = c("Toner Lite", "World Imagery")) %>%
addMarkers(clusterOptions = markerClusterOptions()) %>%
setView(-87.646918, 41.869871, zoom = 13)

map2017
```

