---
title: "**Overview**"
output: 
  html_document:
    toc: true
    toc_float: true
    theme:  flatly
    css: index.css
    includes:
      after_body: footer.html
---
  
## **Motivation**
  
  Due to the cases that happened in Chicago recently, the crime rates in different areas of Chicago caught our attention. Violent incidents in Chicago are of increasing concern over the last few years, and we are interested in looking at what might be associated with increased violence in Chicago. We are concerned about people’s living safety in the city and motivated to find safer neighborhoods for living in Chicago.

## **Related work**

  Apart from that, news came that Zheng, a 24-year-old native of of China’s Sichuan province, was shot and killed on November 9th during a robbery in the 900 block of East 54th Place, which was in the vicinity of University of Chicago's campus. As his compatriots, we were all overwhelmed by unbearable sorrow and loss. And such tragedies kept occuring every now and then. Therefore, our concern towards the crimes in Chicago grew.
  
  [News Source](https://blockclubchicago.org/2021/11/15/man-charged-with-murder-in-killing-of-uchicago-graduate-in-hyde-park/)
  
## **Data Source**

* 6-year Chicago crime data records (2016 - 2021):
  - [2016](https://data.cityofchicago.org/Public-Safety/Crimes-2016/kf95-mnd6/data)
  - [2017](https://data.cityofchicago.org/Public-Safety/Crimes-2017/d62x-nvdr/data)
  - [2018](https://data.cityofchicago.org/Public-Safety/Crimes-2018/3i3m-jwuy/data)
  - [2019](https://data.cityofchicago.org/Public-Safety/Crimes-2019/w98m-zvie/data)
  - [2020](https://data.cityofchicago.org/Public-Safety/Crimes-2020/qzdf-xmn8/data)
  - [2021](https://data.cityofchicago.org/Public-Safety/Crimes-2021/dwme-t96c/data)

* Chicago Data Portal



## **Research Question**

Question 1:

## **Main Results**

## **Conclusion**

